version: "3.9"
services:
  postgres-test:
    image: postgres:17-alpine
    container_name: coin_manager_db_test
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: coin_manager_test
    volumes:
      - pgdata-test:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-net

  node-test:
    build: ./back-end
    container_name: coin_manager_backend_test
    depends_on:
      postgres-test:
        condition: service_healthy
    env_file:
      - ./back-end/.env.test
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate deploy &&
             npm run test"
    networks:
      - test-net

volumes:
  pgdata-test:

networks:
  test-net:
